version: '3'
services:
  app:
    build: .
    image: app:latest
    container_name: app
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=occo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata: